### ISSUE TITLE
Change theme colours of the app

### ISSUE THREAD

**Issue by marcuspang** [marcuspang/we-wallet#4]
Use some website like coolers.co to change the main colours of the app

**Comment by AllardQuek** [comment]
How about yellow (primary colour) and light blue (secondary): https://coolors.co/eff9f0-fdc921-fdd85d-99d6ea-13070c 
![ETH Munich](https://github.com/marcuspang/app-monorepo/assets/40263305/aac1603e-bbe5-4f18-8fc0-50fab55c5d62)

**Comment by AllardQuek** [comment]
Gradients: https://www.eggradients.com/category/yellow-gradient 
Figma: https://www.figma.com/file/RmznVxbcnCwYCu6gZXEpFA/Apple-Wallet-Pass-Kit-(Community)?type=design&node-id=9%3A2660&mode=design&t=ft3fT0mKtr6eUS4r-1
